### PR TITLE
add folia javadoc

### PR DESCRIPTION
**Pull request by powercasgamer**

### CODE REVIEW

**Comment by MiniDigger** [comment]
idk if you can see the logs, but deployment failed because of prettier checks

**Comment by powercasgamer** [comment]
> idk if you can see the logs, but deployment failed because of prettier checks

Can't see logs no. Fixed

**Review by MiniDigger — APPROVED** [review]

**Comment by Machine-Maker** [comment]
Is there any plan for a separate icon for Folia? I think it just looks a little odd now with all white icons and 2 of them being the same and next to each other. Maybe it can be fixed by separating Paper and Folia, but idk if that's enough. 
image

**Comment by powercasgamer** [comment]
I couldn't find a folia.svg in the brand directory so I just went with paper's icon since that's also used [here](https://papermc.io/software/folia).

**Comment by olijeffers0n** [comment]
I spent ages looking for the folia Javadocs earlier... Was gonna PR this but then saw it was already here. Do you have an internal Folia Icon or are we waiting for one to be created?

**Comment by Machine-Maker** [comment]
This icon is used on hangar for the `Supports Folia` tag https://pictogrammers.com/library/mdi/icon/leaf/

**Review by MiniDigger — APPROVED** [review]

**Review by olijeffers0n — APPROVED** [review]

**Review by Machine-Maker — APPROVED** [review]

**Pull request merged**
