### PR TITLE
Migrate away from Vercel

### PR DESCRIPTION
**Pull request by powercasgamer**
Just does previews for now.

just pretend the package stuff isn't there 

Partially addresses #105

### CODE REVIEW

**Comment by MiniDigger** [comment]
considering production is hosted elsewhere, this will fully address #105, no?

**Comment by powercasgamer** [comment]
> considering production is hosted elsewhere, this will fully address #105, no?

I believe so yes? I said partially since I'm not sure what's in the infra issue. Or if the plan was to eventually fully move it to CF.

**Comment by kashike** [comment]
rebase please!

**Comment by powercasgamer** [comment]
> rebase please!

Done, the lockfile and package.json got changed but that's likely because I'm using corepack since papermc/docs also uses that.

**Review by kashike — APPROVED** [review]

**Pull request merged**
